# Generated by Django 6.0.6 on 2026-06-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_bracketprediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="draws",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="games_played",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="goals_against",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="goals_for",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="losses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="wins",
            field=models.IntegerField(default=0),
        ),
    ]
